package com.taxi.repository;

import java.util.List;

/**
 * Repository methods that need custom implementation - cannot be generated by
 * Spring Data.
 * 
 */
public interface TaxiRepositoryCustom {
    Long count(Double latitude, Double longitude, Integer radius, int secondsFrom, int secondsTo);

    /**
     * SELECT DISTINCT ON(taxi_id) ST_Distance_Sphere(
		ST_GeomFromText('POINT(19.938759 50.062208)',4326),
		location
	) as distance, taxi_id  FROM taxi_location ORDER BY taxi_id, timestamp DESC
     * 
     * 
     * @param latitude
     * @param longitude
     * @return
     */
    List getNearest(Double latitude, Double longitude);
}
